language: node_js
node_js:
  - "11"
env:
  - CXX=g++-4.8
  - CI=true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - sudo rm -f /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.14.0/run.sh > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin/
services:
  - docker
notifications:
  email:
  - "me@karlherrick.com"
