language: node_js
node_js:
- '11'
env:
  matrix:
  - CXX=g++-4.8
  - CI=true
  global:
  - secure: kgtchCyxrJDBAA0hs2xLpUuIljK04OB9dsD6M6aCmM/pktleujK9xyGcZoBavaXgdsQuEk6MuEvtYkPAV1qTUamAh8sXoyV/f7e4HybYSL9HzyxyMIulT8UdKbfPgTwvr1uet+VZ5NPO0motTR/OFBERksnFrhEjNR6Uoyq6bXALNf4eU3Cxxb6qPOdv/S/4sWNqeI1V12N6Vrkdk2IXglqogDovhdj9XhWtQWQgKcNEbSUMkjXHG0Lyh3zLX2w1C2prWrQTAXd4aRi6ls+YNFKJVGjdC/hl5R10a4PTp2P9uGuQ3KVplT0jNqy/FLxNNJeT7TOgdRSnlrOE+Q0VgKV0KjtNysF1Aft+ud3t1P1INMPC+ZrT8wayBcXIXqLU3YDt1pXWZOKPErgjiLV0g7HlHH6NZ+xOnYXh281gqhGOxGeZkfDhZKXij3ITDe/oRY3JFt/98GhjsPXD59mkKzDPcCVHyISC0OBTSx2+sryso2iJl04+2NovcLMkewZIEiVB31/1dcFJ/ui9PhR+JayP1qpXaRM90gH0IpPW4FUXg7pOw9OGsubJswnqcwiibbx5KL9gztd2SuX9zvBu35j6xihTNZF5VQywHfHXIxL2PqYoG1FAYnQSmViCzc2r3QymoJ8McYRtUo85kjaOpyAPjAbapPJeGH3iCgBE2m8=
  - secure: OA81CUTsGk0ILf9NPSEjOx7ggICW/j9ngNdrTCJ45jCtK4vlwpHMhLMCLuU63PpbQS+whAueT/DBvfVBYr+AYOZfyuwt+RzlcBFJbsoz/+SFzo2OH6hjqiKQ2hxtTMZWaw3GMAeGgV1iV/JBlQcsrTLgXzc5pZndwX6wD1vSMKYD/aquQjp3MOxITjANhDLqSwWh73DnGgzZsoQ2KtojKh6ih9IIDhmaKzta8387XkUFqpHs+I0Mu/Ivgui88jDB3AEXtEiCRIrFp418vtN8SQFi1GWKpxOzZBH3hLz/aBospWiawRsq9Uwz4p868DjL2R9q6T9BavwxrYTT7aFXTLmUlRqvrYVS7XnvDdT+6fBnpPbU27OcoT31Jt+SPL/WqMmKgvBjw7Vvx8/B3uV+uQxcw+eD1GfZi5CGxtY/kdcV4EeL/kLOQ+cyqupWpfhQJ02JVfdL41g8CcKbFXBqYSa+kxpn3jJHja6XcdGbjZnZxaHxYvZZXbaR+7n+gnYgccE7IRTPNKAT8N7taeKf3Wn1FwS0HpRrp4w/ey9gSiudoh+6f6w6jqZzBeFaBDwCxb0uLiH7ftXtj66dqN8rvZcRY7SFhYW/uL79Fj1RyHe33npxxltDCu15YfwPQ7faze4JTSPDv+sHkkGO964Ftp2O0HXh1l3ReQNVpfJGWWY=
addons:
  sauce_connect: true
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- sudo rm -f /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.14.0/run.sh > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin/
services:
- docker
notifications:
  email:
  - me@karlherrick.com
